### ISSUE TITLE
Calling generate_openapi_document fail when using a method as handler

### ISSUE THREAD

**Issue by nicolas-leydet** [Bogdanp/molten#13]
The following line 

https://github.com/Bogdanp/molten/blob/ef09cd96188b0bc04526a9c26ce26ce31909b406/molten/openapi/documents.py#L170

should probably  be replaced by
 
```python
if not isinstance(handler, (FunctionType, MethodType)):
```

**Comment by Bogdanp** [comment]
Thanks! I fixed this in `0.5.2`.
