### ISSUE TITLE
use https endpoints for unpkg resources

### ISSUE THREAD

**Issue by joranbeasley** [Bogdanp/molten#20]
OpenApiUI Endpoints in index.html use http://unpkg which works fine under most circumstances

however it breaks if you are accessing your molten endpoint over https://  (specifically your OpenAPIUI Endpoint)

the fix is easy ... just use https ... ill put in a merge request soon

**Comment by Bogdanp** [comment]
This is fixed in `0.6.1`. Thanks again!
