### ISSUE TITLE
Ability to test api with Swagger UI to upload file/s

### ISSUE THREAD

**Issue by gurvindersingh** [Bogdanp/molten#23]
As discussed on the [reddit thread](https://www.reddit.com/r/moltenframework/comments/9u7bl9/access_to_uploaded_file_content_and_test_with/) there is issue with current swagger api generation. It does shows the content type option as `multipart/form-data` but doesn't give option to browse and upload the file. 

It might be related to the missing `format: binary` option as mentioned in https://swagger.io/docs/specification/describing-request-body/file-upload/

## What version of molten are you using?

0.7.1

**Comment by gurvindersingh** [comment]
@Bogdanp in case if you want to reproduce the issue, this is the repo which has all the code https://github.com/gurvindersingh/mlapp simply run it using `gunicorn app:app` and its `/predict` route.

Let me know if you need any more info to get this one fixed.

**Comment by Bogdanp** [comment]
Thanks! This should be fixed in 0.7.2, but you're going to have to select the multipart mime type from the UI.

**Comment by Bogdanp** [comment]
@gurvindersingh you have to click "Try it out".

**Comment by gurvindersingh** [comment]
@Bogdanp Sorry for such a silly mistake. Thanks it works :)
