### ISSUE TITLE
Simple OpenAPI doubt

### ISSUE THREAD

**Issue by DNCoelho** [Bogdanp/molten#28]
Hello! Firstly, I would like to thank you for developing such a cool project.

I would like to ask if there is any way to add openAPI specification elements such as tag summaries or action summaries/descriptions in molten. 

If there is no such capability it would be a good addition for future versions. 

Many thanks in advance.

**Comment by Bogdanp** [comment]
You can currently add descriptions to parameters and response codes, but not the actions or tags themselves. Actions' descriptions should be fairly straightforward, but I'm not sure how tag descriptions would fit in off the top of my head. I'm going to mark this as an enhancement.

Check out [these handlers](https://github.com/Bogdanp/molten/blob/master/examples/openapi/petstore/pets.py#L99-L127) for an example of how you can describe parameters.
