### ISSUE TITLE
Empty strings pass schema validation

### ISSUE THREAD

**Issue by ghaaqqq** [Bogdanp/molten#31]
If you had a schema String field, such as 

```
username: str
```

And passed an empty string

```
{
    “username”: “”
}
```

This will not return a 400 error, an empty string will just be passed to the schema object in the view.

I would expect there to be a null or empty style check on strings at least for them to pass validation.

**Comment by Bogdanp** [comment]
This is working as expected. You can specify a minimum length using `field` if you don't want to allow empty strings.
