### ISSUE TITLE
Remove "typing-inspect<0.4" dependency

### ISSUE THREAD

**Issue by akhait** [Bogdanp/molten#35]
Hi,

I was wondering, is it really necessary to have `typing-inspect` version older that 0.4 installed to use Molten? After I removed this requirement from `setup.py`, I was still able to run at least few example scripts from this repo with `typing-inspect-0.5` installed. Is there any reason why someone should use older `typing-inspect` version?

Thanks in advance.

**Comment by androiddrew** [comment]
@akhait Looks like Molten's last change to `setup.py` was back in Feb and the `typing-inspect=0.5` release was in earlier October. This just means that dependencies are getting a little stale on the this project. Maybe you can submit a PR and let the Travis CI prove out at that `typing-inspect=0.5` doesn't have any breaking changes.
