### ISSUE TITLE
docs - motivation - update from API Star to Starlette

### ISSUE THREAD

**Issue by zachvalenta** [Bogdanp/molten#36]
[The motivation page on the doc site](https://moltenframework.com/motivation.html) references API Star as if it's an app framework; it seems that API Star **used to be** an app framework but is [now solely focused on OpenAPI tooling](https://docs.apistar.com/#where-did-the-server-go), with the framework bit now represented by Starlette.

> With version 0.6 onwards the API Star project is being focused as a framework-agnositic suite of API tooling...If you're looking for a high-performance Python-based async framework, then I would instead recommend Starlette.

**Comment by Bogdanp** [comment]
Thanks! I'm sure folks can figure it out though, and given that starlette didn't exist back (and it's quite different afair) then I think the document is still accurate.
