### ISSUE TITLE
Shouldn't the URI be 127.0.0.1 instead of 127.1?

### ISSUE THREAD

**Issue by abhi-jha** [Bogdanp/molten#5]
FILE : https://github.com/Bogdanp/molten/blob/master/docs/source/guide.rst

Example :

`If you then make a curl request to 127.1:8000/hello/Jim you'll get back a JSON response containing the string "Hello Jim!":

$ curl 127.1:8000/hello/Jim
"Hello Jim"`

**Comment by Bogdanp** [comment]
Try it out! :)

`127.1`, `127.0.1` and `127.0.0.1` all represent the same IP address due to the way [inet_aton](https://linux.die.net/man/3/inet_aton) works. This may not be true on Windows, I'm not sure.

**Comment by Bogdanp** [comment]
I just updated the docs to reference `127.0.0.1` instead to avoid any future confusion. Thanks!
