### ISSUE TITLE
Running benchmarks results in timeout

### ISSUE THREAD

**Issue by dgonzo** [Bogdanp/molten#8]
## Checklist

* [X] Does your title concisely summarize the problem?
* [X] Did you include a minimal, reproducible example?
* [X] What OS are you using?
* [X] What version of molten are you using?
* [X] What did you do?
* [X] What did you expect would happen?
* [X] What happened?

## What OS are you using?
macOS 10.13.6

## What version of molten are you using?
molten-0.4.1

## What did you do?
When running the benchmarks for the first time `bench.py` returned a `subprocess.TimeoutExpired`.

## What did you expect would happen?
I expected the benchmarks to run and/or pull and build relevant docker images without manual intervention.

## What happened?
At first I thought it was because I did not have the "python:3.6" docker image already pulled. While that may have contributed after pulling that base image each benchmark test would timeout with a `subprocess.TimeoutExpired` error like:

```python
Traceback (most recent call last):
  File "bench.py", line 157, in <module>
    sys.exit(main())
  File "bench.py", line 140, in main
    build_image(args.framework)
  File "bench.py", line 23, in build_image
    return shell(f"docker build -t bench_{name} -f Dockerfile_{name} .")
  File "bench.py", line 19, in shell
    return subprocess.run(cmd, shell=True, timeout=timeout, stdout=sys.stderr, stderr=sys.stderr)
  File "/Users/gonzo/miniconda3/envs/mltn/lib/python3.7/subprocess.py", line 460, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command 'docker build -t bench_falcon -f Dockerfile_falcon .' timed out after 5 seconds
```

**Comment by Bogdanp** [comment]
Thanks! This should be fixed on master now.
